{
 "title": "Traffic Metrics Dashboard",
 "tags": [ "cCAF" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Application_datasource", "label": "Application Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Incoming Traffic TPS",
   "type": "graph",
   "description": "Incoming Traffic of NCHF Charging, NCHF Ploicy, Diameter Gy, Diameter Sy, SCAPv2 and Diameter VoLTE",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "yaxes": [
    { "format": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum (increase(cha_access_nchf_charging_http_requests_total[1m])) / 60",
     "legendFormat": "NCHF Charging"
    },
    {
     "expr": "sum (increase(cha_access_nchf_policy_http_requests_total[1m])) / 60 ",
     "legendFormat": "NCHF Policy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-Ro-Gy-Gy-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=\"EricssonCharging-Ro-Gy\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy"
    },
    {
     "expr": "sum (increase(cha_access_policy_sy_diameter_requests_total{requestname=~\".*\"}[1m]))/ 60",
     "legendFormat": "Diameter Sy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-SCAPv2-.*\"}[1m]))/ 60",
     "legendFormat": "SCAPv2"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=\"EricssonCharging-SCAPv2\"}[1m]))/ 60",
     "legendFormat": "SCAPv2"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-Ro-VoLTE-MMTel-Ro-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=~\"EricssonCharging-Ro-VoLTE.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE"
    }
   ]
  },
  {
   "title": "Total Outgoing Errors TPS",
   "type": "graph",
   "description": "Outgoing Errors of NCHF Charging, NCHF Policy, Diameter Gy, Diameter Sy, SCAPv2 and Diameter VoLTE",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "yaxes": [
    { "format": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum (increase(cha_access_nchf_charging_http_requests_errors_total[1m])) / 60",
     "legendFormat": "NCHF Charging Errors"
    },
    {
     "expr": "sum (increase(cha_access_nchf_policy_http_requests_errors_total[1m])) / 60 ",
     "legendFormat": "NCHF Policy Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{requestname=~\"EricssonCharging-Ro-Gy-Gy-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{service_context=\"EricssonCharging-Ro-Gy\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy Errors"
    },
    {
     "expr": "sum (increase(cha_access_policy_sy_diameter_requests_errors_total{requestname=~\".*\"}[1m]))/ 60",
     "legendFormat": "Diameter Sy Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{requestname=~\"EricssonCharging-Ro-VoLTE-MMTel-Ro-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{service_context=~\"EricssonCharging-Ro-VoLTE.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{requestname=~\"EricssonCharging-SCAPv2-.*\"}[1m]))/ 60",
     "legendFormat": "SCAPv2 Errors"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_errors_total{service_context=\"EricssonCharging-SCAPv2\"}[1m]))/ 60",
     "legendFormat": "SCAPv2 Errors"
    }
   ]
  },
  {
   "title": "Rate And Charge SBI",
   "type": "graph",
   "description": "NCHF Total request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instanceName) (irate(cha_access_nchf_charging_http_requests_total[$__rate_interval]))",
     "legendFormat": "NCHF Total"
    },
    {
     "expr": "(irate(cha_access_nchf_charging_http_requests_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | NCHF Total | {{operation}}"
    }
   ]
  },
  {
   "title": "Total Access Traffic ",
   "type": "graph",
   "description": "Total access traffic of NCHF Charging, NCHF Policy, Diameter Gy, Diameter Sy, SCAPv2, Diameter VoLTE, External SDP SBI CIR and External SDP CIR (Gy+VoLTE+SCAPv2)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (increase(cha_access_nchf_charging_http_requests_total[1m])) / 60",
     "legendFormat": "NCHF Charging"
    },
    {
     "expr": "sum (increase(cha_access_nchf_policy_http_requests_total[1m])) / 60 ",
     "legendFormat": "NCHF Policy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-Ro-Gy-Gy-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=\"EricssonCharging-Ro-Gy\"}[1m]))/ 60",
     "legendFormat": "Diameter Gy"
    },
    {
     "expr": "sum (increase(cha_access_policy_sy_diameter_requests_total{requestname=~\".*\"}[1m]))/ 60",
     "legendFormat": "Diameter Sy"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-Ro-VoLTE-MMTel-Ro-CCR-.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=~\"EricssonCharging-Ro-VoLTE.*\"}[1m]))/ 60",
     "legendFormat": "Diameter VoLTE"
    },
    {
     "expr": "sum(increase (cha_access_external_rating_diameter_requests_total{requestname=~\"SBI_.*_CIR\"}[1m]))/ 60",
     "legendFormat": "External SDP SBI CIR"
    },
    {
     "expr": "sum(increase (cha_access_external_rating_diameter_requests_total{requestname!~\"SBI_.*|sdp.*\"}[1m]))/ 60",
     "legendFormat": "External SDP CIR (Gy+VoLTE+SCAPv2)"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{requestname=~\"EricssonCharging-SCAPv2-.*\"}[1m]))/ 60",
     "legendFormat": "SCAPv2"
    },
    {
     "expr": "sum(increase(cha_access_rating_diameter_requests_total{service_context=\"EricssonCharging-SCAPv2\"}[1m]))/ 60",
     "legendFormat": "SCAPv2"
    }
   ]
  },
  {
   "title": "Rate And Charge Diameter",
   "type": "graph",
   "description": "NCHF Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(irate(cha_access_rating_diameter_requests_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | NCHF Total | {{requestname}}"
    }
   ]
  },
  {
   "title": "Rate And Charge SBI ERRORS TPS",
   "type": "graph",
   "description": "NCHF and NCHF Policy Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (code,operation) (increase(cha_access_nchf_charging_http_requests_errors_total[1m])) / 60",
     "legendFormat": "TPS NCHF ERRORS | {{operation}} | {{code}}"
    },
    {
     "expr": "sum by (code,operation) (increase(cha_access_nchf_charging_http_requests_errors_total[$__rate_interval]))",
     "legendFormat": "NCHF ERRORS | {{operation}} | {{code}}"
    },
    {
     "expr": "sum by (code,operation) (increase(cha_access_nchf_policy_http_requests_errors_total[$__rate_interval]))",
     "legendFormat": "NCHF POLICY ERRORS | {{operation}} | {{code}}"
    }
   ]
  },
  {
   "title": "External Rating - TPS",
   "type": "graph",
   "description": "External Rating - TPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint,requestname) (irate(cha_access_external_rating_diameter_requests_total[$__rate_interval]))",
     "legendFormat": "SUCCESS | {{endpoint}} | {{requestname}}"
    },
    {
     "expr": "sum by (endpoint,requestname) (irate(cha_access_external_policy_diameter_requests_total[$__rate_interval]))",
     "legendFormat": "SUCCESS POLICY | {{endpoint}} | {{requestname}}"
    },
    {
     "expr": "sum by (endpoint,requestname,code) (irate(cha_access_external_policy_diameter_requests_errors_total[$__rate_interval]))",
     "legendFormat": "ERROR POLICY | {{endpoint}} | {{requestname}} | {{code}}"
    }
   ]
  },
  {
   "title": "Rate And Charge Diameter ERRORS",
   "type": "graph",
   "description": "NCHF, Diameter and TPS-Diameter Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (code,operation,requestname) (increase(cha_access_rating_diameter_requests_errors_total[1m]))",
     "legendFormat": "Diameter ERRORS | {{operation}} | {{requestname}} | {{code}}"
    }
   ]
  },
  {
   "title": "External Rating - Latency",
   "type": "graph",
   "description": "Displays Cha-access external rating diameter request duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (endpoint,quantile) (cha_access_external_rating_diameter_request_duration_seconds)"
    }
   ]
  },
  {
   "title": "CHA-Core - Akka Internal Errors",
   "type": "graph",
   "description": "Displays Cha-core akka internal errors and cha-access routing internal errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(cha_core_rating_akka_requests_errors_total[1m]))",
     "legendFormat": "{{operation}} | {{code}}"
    }
   ]
  },
  {
   "title": "External Rating Request DLB - TPS",
   "type": "graph",
   "description": "Displays Cha-access external rating diameter request duration in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "avg by (requestname,quantile) (cha_access_external_rating_diameter_request_duration_seconds)"
    },
    {
     "expr": "avg by (requestname,quantile) (cha_access_external_rating_diameter_request_duration_seconds{quantile=\"0.95\"})"
    },
    {
     "expr": "sum by (instance,type) (increase (cha_dlb_loadbalancer_diameter_total[1m])) / 60"
    }
   ]
  },
  {
   "title": "CHA-Core - Session Akka Internal Errors",
   "type": "graph",
   "description": "Displays Cha-core - Session Akka internal Errors and Cha-access Akka internal routing Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(cha_core_rating_session_akka_requests_errors_total[1m]))",
     "legendFormat": "{{instance}} | {{session_type}} | {{code}}"
    }
   ]
  },
  {
   "title": "CHA-Access - Akka internal - TPS",
   "type": "graph",
   "description": "Displays ChaAccess - Akka internal requests and errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(cha_access_internal_routing_akka_requests_total[1m])) / 60",
     "legendFormat": "Part-{{customer_partition}} |{{instanceName}} | {{kubernetes_name}} | {{instance}} | {{requestname}}"
    }
   ]
  },
  {
   "title": "Events Created And Processed",
   "type": "graph",
   "description": "Displays Cha-access Event, EDM CFE Fetched, EDM CNFE Fetched, EDM Recovery Fetched, Cha-core Event and EDM CCE Fetched",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instanceName) (irate(cha_access_event_creation_java_total[$__rate_interval]))",
     "legendFormat": "CHA Access Event"
    },
    {
     "expr": "sum by (instanceName)(irate(edm_pub_consume_java_cfe_fetched_total[$__rate_interval]))",
     "legendFormat": "EDM CFE Fetched"
    },
    {
     "expr": "sum by (instanceName)(irate(edm_pub_consume_java_cnfe_fetched_total[$__rate_interval]))",
     "legendFormat": "EDM CNFE Fetched"
    },
    {
     "expr": "sum by (instanceName) (irate(edm_pub_recy_java_fetched_success_total[$__rate_interval]))",
     "legendFormat": "EDM Recovery Fetched"
    },
    {
     "expr": "sum by (instanceName) (irate(cha_core_event_creation_java_total[$__rate_interval]))",
     "legendFormat": "CHA Core Event"
    },
    {
     "expr": "sum by (instanceName)(irate(edm_pub_consume_java_cce_fetched_total[$__rate_interval]))",
     "legendFormat": "EDM CCE Fetched"
    }
   ]
  },
  {
   "title": "Rate And Charge SBI - Response time",
   "type": "graph",
   "description": "Displays Cha-access NCHF charging request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cha_access_nchf_charging_http_request_duration_seconds",
     "legendFormat": "{{instance}} | {{operation}} | {{quantile}}"
    }
   ]
  },
  {
   "title": "EDM Consolidation vs CHA generation, 5min / 300s (EPS)",
   "type": "graph",
   "description": "Displays CHA access event generation, CHA core event generation, EDM CFE Fetched, EDM CNFE Fetched, EDM CFE consolidted, EDM recovery Fetched, EDM CCE Fetched and EDM CCE consolidated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instanceName) (increase(cha_access_event_creation_java_total[5m])) / 300",
     "legendFormat": "CHA Access Event"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_consume_java_cfe_fetched_total[5m])) / 300",
     "legendFormat": "EDM CFE Fetched"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_consume_java_cnfe_fetched_total[5m])) / 300",
     "legendFormat": "EDM CNFE Fetched"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_asn1consol_sftp_cfe_total[5m])) / 300",
     "legendFormat": "EDM CFE Consolidated"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_asn1consol_sftp_cnfe_total[5m])) / 300",
     "legendFormat": "EDM CNFE Consolidated"
    },
    {
     "expr": "sum by (instanceName) (increase(edm_pub_recy_java_fetched_success_total[5m])) / 300",
     "legendFormat": "EDM Recovery Fetched"
    },
    {
     "expr": "sum by (instanceName) (increase(cha_core_event_creation_java_total[5m])) / 300",
     "legendFormat": "CHA Core Event"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_consume_java_cce_fetched_total[5m])) / 300",
     "legendFormat": "EDM CCE Fetched"
    },
    {
     "expr": "sum by (instanceName)(increase(edm_pub_asn1consol_sftp_cce_total[5m])) / 300",
     "legendFormat": "EDM CCE Consolidated"
    }
   ]
  },
  {
   "title": "Diameter - Response time",
   "type": "graph",
   "description": "Displays NCHF charging and Diameter response time\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cha_access_rating_diameter_request_duration_seconds",
     "legendFormat": "{{instance}} | {{requestname}} | {{quantile}}"
    }
   ]
  },
  {
   "title": "Total EDM Events Transferred - Success",
   "type": "graph",
   "description": "Displays EDM CFE, EDM CNFE and EDM CCE \nsuccessful events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(edm_pub_transfer_sftp_success_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_transfer_sftp_failure_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cfe_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cnfe_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cce_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cfe_alternateformat_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cnfe_alternateformat_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1trans_sftp_cce_alternateformat_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1consol_sftp_cfe_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1consol_sftp_cnfe_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1consol_sftp_cce_total[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    }
   ]
  },
  {
   "title": "Average Translation 95,99 - Response Time",
   "type": "graph",
   "description": "Average Translation 95,99 - Response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (quantile) (cha_access_cpm_id_translation_java_request_duration_seconds)"
    }
   ]
  },
  {
   "title": "EDM Consolidated - TPS",
   "type": "graph",
   "description": "Displays EDM CNFE, EDM CCE consolidated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(edm_pub_asn1consol_sftp_cnfe_total[10m])) / 600",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(edm_pub_asn1consol_sftp_cce_total[10m])) / 600",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    }
   ]
  },
  {
   "title": "Average CHA-access CIL - Response Time",
   "type": "graph",
   "description": "Average Cha-access CIL - Response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,quantile,method) (cha_access_cil_data_mgmt_java_request_duration_seconds)"
    }
   ]
  },
  {
   "title": "Total EDM Events Transferred - Failure",
   "type": "graph",
   "description": "EDM Event Publishing failed events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "EDMEventPublishing_EventsTransferredFailure_total\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Core - Charging Converged Rate And Charge",
   "type": "graph",
   "description": "Core - Charging Converged Rate And Charge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(cha_core_rating_akka_request_total{job=\"eric-bss-cha-core\"}[$__rate_interval]))",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}}"
    },
    {
     "expr": "(increase(cha_core_rating_akka_requests_total{direction=\"OUT\"}[1m]))/ 60",
     "legendFormat": "{{instance}} | {{direction}} | {{operation}}"
    },
    {
     "expr": "sum by (code)(increase(cha_core_rating_akka_requests_errors_total{}[1m]))/ 60",
     "legendFormat": "{{instance}} | ERROR | {{direction}} | {{operation}} | {{code}}"
    }
   ]
  },
  {
   "title": "CPM DNS - TPS",
   "type": "graph",
   "description": "Displays MSISDN Provisioning Total, MSISDN Provisioning Success, IMSI Provisioning Total, IMSI Provisioning Success and MSISDN Provisioning Failed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(increase(cpm_provision_msisdn_dns_requests_total[1m])) /60",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | MSISDN Provisioning Total"
    },
    {
     "expr": "(increase(cpm_provision_msisdn_dns_requests_success_total[1m])) /60",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | MSISDN Provisioning Success"
    },
    {
     "expr": "(increase(cpm_provision_imsi_dns_requests_total[1m])) /60",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | IMSI Provisioning Total"
    },
    {
     "expr": "(increase(cpm_provision_imsi_dns_requests_success_total[1m])) /60",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | IMSI Provisioning Success"
    },
    {
     "expr": "(increase(cpm_provision_msisdn_dns_requests_failed_total[1m])) /60",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | MSISDN Provisioning Failed"
    }
   ]
  },
  {
   "title": "Core - Charging Converged Rate And Charge - Response Time",
   "type": "graph",
   "description": "Core - Charging Converged Rate And Charge - Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cha_core_rating_akka_request_duration_seconds{}",
     "legendFormat": "{{instance}}  | {{quantile}}"
    }
   ]
  },
  {
   "title": "CPM DNS - Response Time (max)",
   "type": "graph",
   "description": "Displays MSISDN Provisioning Latency and IMSI Provisioning Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cpm_provision_msisdn_dns_response_duration_seconds_max",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | MSISDN Provisioning Latency"
    },
    {
     "expr": "cpm_provision_imsi_dns_response_duration_seconds_max",
     "legendFormat": "{{instanceName}} | {{kubernetes_name}} | {{instance}} | IMSI Provisioning Latency"
    }
   ]
  },
  {
   "title": "Average CHA-core CIL - Response Time",
   "type": "graph",
   "description": "Average Cha-core CIL - Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,method,quantile) (cha_core_cil_data_mgmt_java_request_duration_seconds)"
    }
   ]
  },
  {
   "title": "Total Charging NRF Registration Requests",
   "type": "graph",
   "description": "Total CHA NRF registration requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(cha_nfreg_nrf_registration_http_requests_total[$__rate_interval])",
     "legendFormat": "{{method}} | {{operation}} | {{instance}}"
    }
   ]
  },
  {
   "title": "CIL Reject",
   "type": "timeseries",
   "description": "Cassandra ECOP rejections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "increase(cassandra_ecop_rejections_total[60s])/60",
     "legendFormat": "{{kubernetes_pod_name}}-{{mechanism}}"
    }
   ]
  }
 ]
}